### PR TITLE
before main

### PR DESCRIPTION
**Pull request by urosmilkovic**

### CODE REVIEW

**Comment by ghost** [comment]
Take a closer look. This section should go to the right.
image

**Comment by urosmilkovic** [comment]
[image: image.png]
Then how do I see it like this ?

пон, 27. сеп 2021. у 21:54 Sandra Ristic ***@***.***> је
написао/ла:

**Comment by urosmilkovic** [comment]
> Take a closer look. This section should go to the right.
> image
On my computer I see it like this
Capture

**Comment by urosmilkovic** [comment]
> Take a closer look. This section should go to the right.
I checked only on Internet Explorer or Microsoft Edge is not working. I tested on Mozilla, Chrome and Safari.
image

**Comment by ghost** [comment]
I'm 

> I checked only on Internet Explorer or Microsoft Edge is not working. I tested on Mozilla, Chrome and Safari.

I use Chrome, Linux. It doesn't work there.

**Comment by ghost** [comment]
image
Check validation. Also, check mobile resolution, landscape.

**Comment by sandraristic7** [comment]
Also, check mobile resolution, landscape.

**Pull request merged**
